-- Trackline — Supabase schema
-- Run this once in your Supabase project's SQL Editor (left menu → SQL Editor → New query).

create table if not exists families (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

-- Row Level Security must be explicitly enabled and given policies, or the
-- anon key (used by the frontend) gets no access at all by default.
alter table families enable row level security;

-- These policies allow anyone with the public "anon" key to read/write any
-- row, AS LONG AS THEY KNOW THE family id. That id is a long random string
-- generated by the app (not guessable) — same trust model as the Azure
-- Function version: security through an unguessable identifier, not per-user
-- authentication. Good enough for a personal family app; see the note at the
-- bottom of SUPABASE_SETUP.md for how to harden this further later with real
-- Supabase Auth if you ever want it.

create policy "allow read by id"
  on families for select
  using (true);

create policy "allow insert"
  on families for insert
  with check (true);

create policy "allow update"
  on families for update
  using (true);
